version: '3.7'
services:
  nginx:
    image: nginx:1.17.10-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80

  apple:
    image: hashicorp/http-echo
    command: -text="apple"

  orange:
    image: hashicorp/http-echo
    command: -text="orange"

  swagger-ui:
    image: swaggerapi/swagger-ui:v3.25.4
    volumes:
      - ./swagger.json:/app/swagger.json
    environment:
      SWAGGER_JSON: /app/swagger.json